//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamePerfReporter {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class S : global::System.Configuration.ApplicationSettingsBase {
        
        private static S defaultInstance = ((S)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new S())));
        
        public static S Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GUID {
            get {
                return ((string)(this["GUID"]));
            }
            set {
                this["GUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Windows.Forms.Keys SuspectedIssueKeyCode {
            get {
                return ((global::System.Windows.Forms.Keys)(this["SuspectedIssueKeyCode"]));
            }
            set {
                this["SuspectedIssueKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTimeStartup {
            get {
                return ((bool)(this["FirstTimeStartup"]));
            }
            set {
                this["FirstTimeStartup"] = value;
            }
        }
    }
}
