// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>GamePerformanceReporter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace GamePerformanceReporter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.37595")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="GamePerformanceReporter")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GamePerformanceReporter", IsNullable=false)]
    public partial class Report {
        
        private string reportIDField;
        
        private System.DateTime dateTimeSubmittedField;
        
        private string systemGUIDField;
        
        private bool processedField;
        
        private System.DateTime processedDateField;
        
        private bool processInProgressField;
        
        private List<ReportFile> reportFileField;
        
        private List<ReportAttribute> reportAttributeField;
        
        public Report() {
            this.reportAttributeField = new List<ReportAttribute>();
            this.reportFileField = new List<ReportFile>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DateTimeSubmitted {
            get {
                return this.dateTimeSubmittedField;
            }
            set {
                this.dateTimeSubmittedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SystemGUID {
            get {
                return this.systemGUIDField;
            }
            set {
                this.systemGUIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Processed {
            get {
                return this.processedField;
            }
            set {
                this.processedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ProcessedDate {
            get {
                return this.processedDateField;
            }
            set {
                this.processedDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ProcessInProgress {
            get {
                return this.processInProgressField;
            }
            set {
                this.processInProgressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportFile", Order=6)]
        public List<ReportFile> ReportFile {
            get {
                return this.reportFileField;
            }
            set {
                this.reportFileField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportAttribute", Order=7)]
        public List<ReportAttribute> ReportAttribute {
            get {
                return this.reportAttributeField;
            }
            set {
                this.reportAttributeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.37595")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="GamePerformanceReporter")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GamePerformanceReporter", IsNullable=false)]
    public partial class ReportFile {
        
        private string fileTypeField;
        
        private string fileNameField;
        
        private string fileHashField;
        
        private uint fileSizeBytesField;
        
        private string uRLField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileHash {
            get {
                return this.fileHashField;
            }
            set {
                this.fileHashField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public uint FileSizeBytes {
            get {
                return this.fileSizeBytesField;
            }
            set {
                this.fileSizeBytesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.37595")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="GamePerformanceReporter")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GamePerformanceReporter", IsNullable=false)]
    public partial class ReportAttribute {
        
        private string keyField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.37595")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="GamePerformanceReporter")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GamePerformanceReporter", IsNullable=false)]
    public partial class ProcessingRecord {
        
        private string reportIDField;
        
        private string instanceField;
        
        private System.DateTime dateTimeStartedField;
        
        private System.DateTime dateTimeEndedField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReportID {
            get {
                return this.reportIDField;
            }
            set {
                this.reportIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Instance {
            get {
                return this.instanceField;
            }
            set {
                this.instanceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DateTimeStarted {
            get {
                return this.dateTimeStartedField;
            }
            set {
                this.dateTimeStartedField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DateTimeEnded {
            get {
                return this.dateTimeEndedField;
            }
            set {
                this.dateTimeEndedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.37595")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="GamePerformanceReporter")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="GamePerformanceReporter", IsNullable=false)]
    public partial class ProcessingRecords {
        
        private List<ProcessingRecord> processingRecordField;
        
        public ProcessingRecords() {
            this.processingRecordField = new List<ProcessingRecord>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ProcessingRecord", Order=0)]
        public List<ProcessingRecord> ProcessingRecord {
            get {
                return this.processingRecordField;
            }
            set {
                this.processingRecordField = value;
            }
        }
    }
}
